### ISSUE TITLE
Mark homework 1, exercise3 of Ruifeng Chen

### ISSUE THREAD

**Issue by ruifengchen** [ruifengchen/stat679work#3]
Dear Professor Ane, 

I have submitted hw1, exercise3. 

The SHA is https://github.com/ruifengchen/stat679work/commit/e9f0c5ae7cf64d11c13ff27b2bf0bbf0745df1a0
All I did are in the directory [hw1](https://github.com/ruifengchen/stat679work/tree/master/hw1)
Besides, the details are in [readme.md](https://github.com/ruifengchen/stat679work/blob/master/hw1/readme.md)

Thanks for your attention!@cecileane

Best,
Ruifeng

**Comment by jbadger3** [comment]
Ruifeng,

Excellent work.  I was able to get your code running and it looks like you have used some features of shell programming that we haven't used in class.  Very clever!  A couple of important notes.  I think the weakest part of your submission was in the documentation.  I didn't see anywhere in your readme.md which relative path to run your scripts from.  normarlizeFileNames.sh had to be run from /stats679work and summarizeSNaQres.sh from /hw1.  It would have been useful to see a complete organized list from A-B that shows all the shell commands/scripts to recreate the results.  Also, I noticed in your markdown text you did not include spaces between ## and your titles, so this didn't display nicely on my computer.  Overall though, I thought you did a great job.  Just a bit more work on documentation!  Cheers.  Jon

**Comment by IcecreamWine** [comment]
Hi Ruifeng,

Great job. It is great that you make descriptions of all files and folders in `hw1/`. However, it will be more clear if you organize all scripts in one folder such as `scripts/` and then you can add more script details in `scripts/readme.md`. You did not document how to use your scripts in `readme.md` or issue. So I did not know from which directory to run them. I run `summarizeSNaQres.sh` in `hw1/` and it works well. Glad you use `cut` but sometimes `sed` is more convenient and it would be useful if you practice more `sed` and *extended* regular expressions. Also, it would be great if you find a way to build this summary file with a single loop instead of 3 loops. And it would be more straightforward if you create a result directly instead of pasting three intermediate csv files into one and then deleting them. 

Best,
Yijing

**Comment by IcecreamWine** [comment]
Hi Ruifeng,

I just forgot a little thing. For exercise 3 I think *below* 3460 means *less than* 3460 rather than *less or equal to* 3460 which means you can change `le` to `lt` in your if statement. Sorry for bothering you again!

Best,
Yijing

**Comment by cecileane** [comment]
I agree: thanks for identifying this bug Yijing. If the original value was `3460.6123` (just as an example), your script using `grep` than `sed` online 70 would set `loglik=3460`. So your current code using `le` would identify the log-likelihood value as being less than or equal to 3460, when in fact, the original value was *greater* than 3460. You can fix this bug by replacing `le` by `lt`. Thanks Yijing for catching this!
