### ISSUE TITLE
Mark homework 2 of Ruifeng Chen

### ISSUE THREAD

**Issue by ruifengchen** [ruifengchen/stat679work#4]
Dear Professor Ane,

I have submitted hw2

The SHA is [db28646](https://github.com/ruifengchen/stat679work/commit/db286463cb97d5e5158cbd7952ecf8a3bc6b196e)
All I did are in the directory [hw2](https://github.com/ruifengchen/stat679work/tree/master/hw2)
Besides, the details are in [readme.md](https://github.com/ruifengchen/stat679work/blob/master/hw2/readme.md)

Thanks for your attention!@cecileane

Best,
Ruifeng

**Comment by cecileane** [comment]
Hi Ruifeng,

Very nice job! Your work was easy to go through, and your script worked. More details below.

## overall presentation

I like that you organized your project with separate directories for your script / input / output files. Great job with that!

Great use of markdown style! Even your github issue message had a link to your hw2 folder. You should use code blocks for code and file names, though (with single or triple backticks), especially at the end of your readme file in the section "Execution" and in your `script/readme.md`

It's interesting that you had 2 scripts, your instructions to run them are clear. It is very often that we want to make one choice or another --here add a comma or not. The best way to deal with this is not with 2 different scripts, but with a single script that takes an extra option, here an option `--add-comma` for example.

## running your script

The correct script here is `script/hw2_no_comma_last_column.py`, with this output:

    "#","Date Time","Temperature","Energy Value(kWh)"
    1,07/29/16 10:26:34 AM,72.86,
    2,07/29/16 11:26:34 AM,73.92,
    3,07/29/16 12:26:34 PM,73.98,
    ...
    13,07/29/16 10:26:34 PM,73.27,
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30,
    ...

For the file to have a correct format, each line should have the exact same number of commas (except perhaps for commas within quoted blocks): because the number of columns should be the same in all rows. In the output above, each row has 3 commas, so 4 columns. If you add a comma to each line that does not have an energy values, then these lines have 5 columns instead of 4, and the lines with an energy value have 4 columns only. That's not a constant number of columns and that's bad. As you saw, github is unhappy with this as well.

The other problem with this output is that lines with no energy values have a space after the final comma. For instance, the first line has this "1,07/29/16 10:26:34 AM,72.86, " instead of this: "1,07/29/16 10:26:34 AM,72.86,". The problem with this final space is that the cell has a space instead of nothing. If you read such a file with R, R will have to interpret the last column as a column of characters to accommodate the spaces, instead of a column of numbers (and many cells with a missing value). So these spaces will cause issues for downstream analyses.

## about your code

Great checking for the expected number of arguments. It would have been best to use the argparse library, and to check for the existence of the output file before overwriting it.

Your file has a single big function for the most part. Well, there are 2 small functions defined inside, like `check_order`. They use nothing else than their own arguments (like month and day). So it would have been best to move the definition of this `check_order` function outside of the big `mergy_files` function. Same thing for the other small function `check_time`.

Your main function `mergy_files(..., output = "output.csv")` has a wrong default for the `output` argument: it should be a file handle, not a file name (based on how it's used on lines 109-110: `output.write(...)`). So a better choice would have been `output = sys.stdout`. Also, the check to avoid overwriting a file would never work given that `output` should be a file handle:

```python
if output == "hw2-datamerge/.*.csv":  #prevent overwriting existing files unintentionally.
    print("Error! Overwrite existing files!")
```

In this check, the string `"hw2-datamerge/.*.csv"` is not expanded by the shell anyway.

Regarding comments, you have many, but many are not useful. For example, on this line it is obvious that the value of variable `n_energy` is set to 1, so the comment does not bring much:

```python
n_energy = 1  #set the n_energy value
```

As another example, a more helpful comment might have been "get the temperature" on line 80:

```python
value = re.sub(r'.*,(\d+.*)', r'\1', line)  #get the value
```

You have excellent use of regular expressions!

**Comment by ruifengchen** [comment]
Dear Professor Ane,


Thank you!


Best,

Ruifeng

________________________________
